name:                refine
version:             0.1.0.0
github:              "err0r500/refine"
license:             GPL-3
author:              "Matthieu Jacquot"
maintainer:          "matthieu.jacquot.tech@protonmail.ch"
copyright:           "2020 Matthieu Jacquot"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/err0r500/refine#readme>

default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude
  - ConstraintKinds
  - FlexibleContexts
  - RankNTypes
  - GeneralizedNewtypeDeriving
  - MonoLocalBinds

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- mtl
- data-has
- lens >= 4 && < 5
- katip >= 0.8.4.0
- scotty
- wai
- wai-extra
- warp
- http-types
- exceptions >= 0.10.4

library:
  source-dirs: src

executables:
  refine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - refine

tests:
  refine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - refine
    - hspec-discover
    - hspec
